## Programming Assignment 8

1.	Write a Python Program to Add Two Matrices?

In [2]:
# Program to add two matrices using nested loop
X = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
Y = [[5, 8, 1], [6, 7, 3], [4, 5, 9]]

# Initialize an empty matrix for the result
result = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# Iterate through rows
for i in range(len(X)):
    # Iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

# Print the result
for r in result:
    print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [1]:
# Program to add two matrices using list comprehension
X = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
Y = [[5, 8, 1], [6, 7, 3], [4, 5, 9]]

# Calculate the result using list comprehension
result = [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]

# Print the result
for r in result:
    print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


2.	Write a Python Program to Multiply Two Matrices?

In [5]:
# Define two matrices (adjust the values as needed)
X = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
Y = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

# Initialize the result matrix with zeros
result = [[0] * len(Y[0]) for _ in range(len(X))]

# Multiply matrices X and Y
for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

# Display the result
for row in result:
    print(row)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [8]:
import numpy as np

# Define matrices (same as above)
X = np.array([[12, 7, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]])

# Multiply matrices using NumPy
result = np.dot(X, Y)

# Print the result
print(result)


[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


3.	Write a Python Program to Transpose a Matrix?

In [9]:
import numpy as np

# Define matrix X (same as above)
X = np.array([[12, 7], [4, 5], [3, 8]])

# Transpose using NumPy
result = X.T

# Print the transposed matrix
print(result)


[[12  4  3]
 [ 7  5  8]]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [10]:
my_str = "Hello this Is an Example With cased letters"

# Convert the string to lowercase and split into words
words = [word.lower() for word in my_str.split()]

# Sort the list of words
words.sort()

# Display the sorted words
print("The sorted words are:")
for word in words:
    print(word)


The sorted words are:
an
cased
example
hello
is
letters
this
with


5.	Write a Python Program to Remove Punctuation From a String?

In [3]:
# Define punctuation characters
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# Input string (you can also take input from the user)
my_str = "Hello!!!, he said ---and went."

# Remove punctuation from the string
no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct += char

# Display the unpunctuated string
print(no_punct)


Hello he said and went


In [4]:
import string

def remove_punctuations(text):
    for c in string.punctuation:
        text = text.replace(c, "")
    return text

# Example usage
text_with_punctuations = "String! With, some; punctuations."
cleaned_text = remove_punctuations(text_with_punctuations)
print(cleaned_text)


String With some punctuations
